name: generate metrics
on:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  my-metrics:
    runs-on: ubuntu-slim
    steps:
      - name: main-acc
        uses: lowlighter/metrics@latest
        with:
          # Output
          filename: files/main-acc.svg

          # Your GitHub token
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: ccnmxns
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Madrid


      - name: topics
        uses: lowlighter/metrics@latest
        with:
          # Output
          filename: files/topics.svg

          # Your GitHub token
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: ccnmxns
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons



      - name: languages
        uses: lowlighter/metrics@latest
        with:
          # Output
          filename: files/langs.svg

          # Your GitHub token
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: ccnmxns
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_categories: data, markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8

      - name: music
        uses: lowlighter/metrics@latest
        with:
          # Output
          filename: files/music.svg

          # Your GitHub token
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          template: classic
          plugin_music: yes
          plugin_music_playlist: https://music.apple.com/es/playlist/usr-share/pl.u-gxblkLlIW9G7Ke?l=en
          plugin_music_limit: 3