name: generate metrics
on:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  my-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: main-chunk
        uses: lowlighter/metrics@latest
        with:
          # Output
          filename: metrics.plugin.chunk.svg

          # Your GitHub token
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: ccnmxns
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Madrid

          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons

          plugin_languages: yes
          plugin_languages_categories: data, markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8

          plugin_music: yes
          plugin_music_provider: apple
          plugin_music_playlist: https://embed.music.apple.com/es/playlist/usr-share/pl.u-gxblkLlIW9G7Ke?l=en
          plugin_music_limit: 3